# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
    - arm64
  ldflags:
    - -extldflags -static
    - -s -w
    - -X github.com/cnrancher/rancher-flat-network/pkg/utils.GitCommit={{.Env.COMMIT}}
    - -X github.com/cnrancher/rancher-flat-network/pkg/utils.Version={{.Env.TAG}}
  main: ./main.go
  id: rancher-flat-network-operator
  binary: rancher-flat-network-operator
- env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
    - arm64
  ldflags:
    - -extldflags -static
    - -s -w
    - -X github.com/cnrancher/rancher-flat-network/pkg/utils.GitCommit={{.Env.COMMIT}}
    - -X github.com/cnrancher/rancher-flat-network/pkg/utils.Version={{.Env.TAG}}
  main: ./cni/main.go
  id: rancher-flat-network-cni
  binary: rancher-flat-network-cni
- env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
    - arm64
  ldflags:
    - -extldflags -static
    - -s -w
    - -X github.com/cnrancher/rancher-flat-network/pkg/utils.GitCommit={{.Env.COMMIT}}
    - -X github.com/cnrancher/rancher-flat-network/pkg/utils.Version={{.Env.TAG}}
  main: ./migrator/main.go
  id: rancher-flat-network-migrator
  binary: rancher-flat-network-migrator

release:
  prerelease: auto

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
